# WaterDizzle Configuration
# A journey of 1,000 lines starts with a single char

# Language Settings
# Default language: ru_ru
language: "ru_ru"

# Distance in blocks outside of zone we track thrown items
item_lookup_distance_modifier: 10