main: ${PACKAGE}.${NAME}
name: ${NAME}
version: "${VERSION}"
api-version: "1.21.5"
author: RozeFound
description: Water damage zone plugin for Minecraft
commands:
  zone:
    description: Manage damage zone anchors
    usage: "/zone <set1|set2|info|particles> [x] [y] [z]"
    permission: waterdizzle.zone
permissions:
  waterdizzle.zone:
    description: Permission to manage damage zone anchors
    default: op
